### ISSUE TITLE
mac80211 net stack and usb wireless drivers. [device doesn't boot]

### ISSUE THREAD

**Issue by discipuloosho** [B14CKB1RD-Kernel/B14CKB1RD_Kernel_N6#2]
I have seem that when I build with B14CKB1RD_defconfig and I active mac80211 stack and usb wireless drivers, device doesn't boot.
No problem with default shamu_defconfig + mac80211 stack + all wireless usb drivers (atheros, ralink, realtek, etc).
Both in mm6.0 branch, of course.
What can be the cause? I don't understand where is the problem. :S

**Comment by discipuloosho** [comment]
Atheros usb wireless drivers, specifically.

**Comment by REV3NT3CH** [comment]
ill look into it. why exactly is this needed enabled on shamu though?

**Comment by discipuloosho** [comment]
Because `a1ad0329c71d6576fda340a02cc07e76e9338f63` commit set usb wireless drivers in monitor mode.

**Comment by discipuloosho** [comment]
It's very strange. This only happens in flar2 elementalx kernel too. So, perhaps it could be a flar2 patch into your kernel. I don't know ... maybe.

**Comment by REV3NT3CH** [comment]
do you have a hangouts or other means to contact you at besides here? if you do reach me at rev3nt3ch@gmail.com
